name: async_preferences
description: A flutter plugin to use local preferences asynchronously.
version: 0.3.0
author: David Serrano Canales <svprdga>
homepage: https://appblaze.io

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.svprdga.async_preferences
        pluginClass: AsyncPreferencesPlugin
      ios:
        pluginClass: AsyncPreferencesPlugin